artifact_location: file:///D:/UsingSpace/Projects/Artificial Intelligent/ComputerVision/ObjectDetection/YOLO/Light
  Control Using Hand Movement/Yolo-Weights/runs/mlflow/140044747503976243
creation_time: 1719996856329
experiment_id: '140044747503976243'
last_update_time: 1719996856329
lifecycle_stage: active
name: /Shared/YOLOv8
