artifact_location: file:///D:/UsingSpace/Projects/Artificial Intelligent/ComputerVision/ObjectDetection/YOLO/Light
  Control Using Hand Movement/Yolo-Weights/runs/mlflow/0
creation_time: 1719996856276
experiment_id: '0'
last_update_time: 1719996856276
lifecycle_stage: active
name: Default
